### ISSUE TITLE
Animation restart every time i make a change to other elements of ui

### ISSUE THREAD

**Issue by lorenzo-gangemi** [glomadrian/Grav#6]
I'm trying to implement this library in my project, but i can't get over this problem.
Every time I make a change to the ui, like showing or hiding a ProgressBar, the animation restarts.

`<view
        android:id="@+id/view2"
        class="com.github.glomadrian.grav.GravView"
        id="@+id/view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:animationGenerators="@array/FalconAnimations"
        app:array_colors="@array/Spectral"
        app:ball_size_from_size="3dp"
        app:ball_size_to_size="5dp"
        app:colorGenerator="com.github.glomadrian.grav.generator.paint.ArrayColorGenerator"
        app:gravGenerator="com.github.glomadrian.grav.generator.grav.BallGenerator"
        app:pointGenerator="com.github.glomadrian.grav.generator.point.RegularPointGenerator"
        app:regular_cell_size="250"
        app:regular_variance="200"
        app:shake_direction="horizontal"
        app:shake_variance="15dp"
        app:side_to_side_direction="downToUp"
        app:side_to_side_max_duration="6000"
        app:side_to_side_min_duration="3000"
        tools:layout_editor_absoluteX="0dp"
        tools:layout_editor_absoluteY="0dp" />`

**Comment by glomadrian** [comment]
yes, it was a bug with the OnGlobalLayoutListener, is fixed in **V1.1**
